name: CI-DockerBuild

on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install OC CLI
        run: |
          curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc /usr/local/bin/
          oc version
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
      - name: Log in Openshift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: https://api.rm1.0a51.p1.openshiftapps.com:6443
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: Deploy files
        run: |
          helm upgrade --install my-mongodb oci://registry-1.docker.io/cloudpirates/mongodb -f values.yaml
